dataset_cfg: dataset/PEMS-BAY.yaml # Override from CLI the dataset to run the experiment on
cross_learning: True
batch_size: null
stride_steps: 1
seed: 42
quantile_levels: [0.1, 0.5, 0.9]

wandb:
  enabled: true
  entity: null
  run_name: baseline_1_0
  tags: []